name: Python Project CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r weatherApp/requirements.txt

      - name: Run Tests
        run: pytest
        working-directory: weatherApp/tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

#      - name: Copy files via scp
#        env:
#          KEY: ${{ secrets.EC2_KEY }}
#        run: |
#          scp -i "$KEY" -o StrictHostKeyChecking=no -r ./ admin@172.31.4.89:~/DevOpsApplication

      - name: Deploy to AWS
        run: |
          ssh -i "Test-Server-Key.pem" admin@ec2-3-17-166-233.us-east-2.compute.amazonaws.com
          cd DevOpsApplication
          npm install --production
          pm2 restart DevOpsApplication