name: Python Project CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
        working-directory: weatherApp/tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set Up SSH
        env:
          KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh 
          cp ./Test-Server-Key.pem ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ec2-3-17-166-233.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to AWS
        run: |
          ssh -i ~/.ssh/deploy_key admin@ec2-3-17-166-233.us-east-2.compute.amazonaws.com << 'EOF'
          sudo apt-get update -y
          sudo apt-get install -y git python3 python3-venv
          
          cd ~
          if [ ! -d "DevOpsApplication" ]; then
            git clone https://github.com/your-repo.git DevOpsApplication
          fi
          cd DevOpsApplication
          
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          EOF