name: Python Project CI/CD Pipeline # No Deployment yet, need AWS server for that (HUNTER!!!)

on:
  push:
    branches:
      - main
      - first-branch # Not sure what the purpose of first-branch is, it's literally the same as main, included it anyway
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r weatherApp/requirements.txt

      - name: Run Tests
        run: |
          pytest

# All CI/CD pipeline's supposed to do is run tests and make sure they work.. I dunno :3