name: Python Project CI/CD Pipeline # No Deployment yet, need AWS server for that (HUNTER!!!)

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r weatherApp/requirements.txt

      - name: Run Tests
        run: |
          pytest